name: BedwarsRelAutoConfig
version: ${project.version}
main: com.brac.BedwarsRelAutoConfig
author: Ver_zhzh
description: BedwarsRel多配置管理插件

depend: [BedwarsRel]
softdepend: [BedwarsScoreBoardAddon, BedwarsItemAddon]

commands:
  brac:
    description: BedwarsRel自动配置管理主命令
    usage: |
      §e/brac create <类型> <名称> §7- 创建新的配置模板
      §e/brac enable <游戏名> <类型> <名称> §7- 为游戏启用自定义配置
      §e/brac disable <游戏名> <类型> §7- 为游戏禁用自定义配置
      §e/brac delete <类型> <名称> [confirm] §7- 删除配置模板
      §e/brac list §7- 列出所有配置和映射关系
      §e/brac reload §7- 重载插件配置
      §e/brac RandomEnable <游戏名> [类型] §7- 随机启用配置
      §e/brac RandomOut <游戏名> <类型> [名称] §7- 设置随机排除
      §e/brac help §7- 显示帮助信息
    aliases: [bedwarsrelautoconfig, bracfg]

permissions:
  brac.*:
    description: 允许使用所有BRAC命令
    default: op
    children:
      brac.create: true
      brac.enable: true
      brac.disable: true
      brac.delete: true
      brac.list: true
      brac.reload: true
      brac.randomenable: true
      brac.randomout: true
  brac.create:
    description: 允许创建配置模板
    default: op
  brac.enable:
    description: 允许为游戏启用自定义配置
    default: op
  brac.disable:
    description: 允许为游戏禁用自定义配置
    default: op
  brac.delete:
    description: 允许删除配置模板
    default: op
  brac.list:
    description: 允许列出配置和映射关系
    default: op
  brac.reload:
    description: 允许重载插件配置
    default: op
  brac.randomenable:
    description: 允许随机启用配置
    default: op
  brac.randomout:
    description: 允许设置随机排除
    default: op

