name: BedwarsItemAddon
main: me.ram.bedwarsitemaddon.Main
version: 1.7.0
author: Ram
depend: [ BedwarsRel, ProtocolLib ]
softdepend: [ BedwarsScoreBoardAddon ]
website: "https://github.com/TheRamU/BedwarsItemAddon"

commands:
  bedwarsitemaddon:
    aliases: [ bwia ]

permissions:
  bedwarsitemaddon.reload:
    default: op
  bedwarsitemaddon.updatecheck:
    default: op
